name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PG_VER: 16    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PostgreSQL
      uses: tj-actions/install-postgresql@v3
      with:
        postgresql-version: ${{ env.PG_VER }}
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y postgresql-server-dev-${{ env.PG_VER }}
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make install
      run: sudo make install
    - name: Start PostgreSQL service
      run: sudo systemctl start postgresql.service
    - name: Add extension to PostgreSQL
      run: sudo -u postgres psql postgres -c "CREATE EXTENSION pg_sendmail"
    - name: Install sendmail
      run: sudo apt install -y sendmail
    - name: Test extension pg_sendmail 
      run: sudo -u postgres psql postgres -c "EXPLAIN ANALYZE (FORMAT YAML, TIMING true) SELECT sendmail('psql@localhost', 'root@localhost', 'test mail', E'Hi.\nThis is test e-mail message.')"

#      auto_tests:
#        name: Auto Tests    
#        runs-on: ubuntu-latest
#        needs: build
#        steps: