name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PG_VER: 17    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PostgreSQL
      uses: tj-actions/install-postgresql@v3
      with:
        postgresql-version: ${{ env.PG_VER }}
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y postgresql postgresql-contrib postgresql-common
        sudo apt install -y libpq-dev postgresql-server-dev-${{ env.PG_VER }}
#        sudo -u postgres psql -f setup.sql
    - uses: actions/checkout@v4
#    - name: configure
#      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make install
      run: sudo make install
    - name: Start PostgreSQL service
      run: sudo systemctl start postgresql.service
    - name: Add extension to PostgreSQL
      run: sudo -u postgres psql postgres -c "CREATE EXTENSION pg_sendmail"
